"use client";

import { allRoutes } from "../../Routes/AllRoutes";
import EntityDetailsPage from "../ReusablePages/EntityDetailsPage";
import { commonAdsTableHeaders } from "../Ads/Ads";
import { useTranslation } from "react-i18next";
import { getAdsOfBrand } from "../../Services/adsService";

const BrandDetails = () => {
  const { t } = useTranslation();

  return (
    <EntityDetailsPage
      entityType='Brand'
      editRoute={allRoutes.EDIT_BRAND}
      backRoute={allRoutes.BRANDS}
      getExtraSectionData={(data: any) => ({
        getItemsFn: getAdsOfBrand,
        headers: commonAdsTableHeaders,
        heading: `${t("Ads of")} ${data?.name || t("Brand")}`,
        subHeading: `${t("These are all the Ads of")} ${
          data?.name || t("Brand")
        }`,
        emptyStateMessage: `${t("There are no ads generated by")} ${
          data?.name || t("Brand")
        }`,
        detailsPagePath: allRoutes.VIEW_AD,
      })}
    />
  );
};

export default BrandDetails;
