import { shuffleArray } from "@/app/Utils/utils";

export function getShuffledQuestions() {
  // Filter by difficulty
  const easy = shuffleArray(
    questions.filter((q) => q.difficulty === "easy")
  ).slice(0, 6);
  const medium = shuffleArray(
    questions.filter((q) => q.difficulty === "medium")
  ).slice(0, 7);
  const hard = shuffleArray(
    questions.filter((q) => q.difficulty === "hard")
  ).slice(0, 7);

  // Combine and return
  return [...easy, ...medium, ...hard];
}

// All Questions

export const questions = [
  {
    question: "What is the capital of France?",
    options: ["Paris", "Rome", "Madrid", "Berlin"],
    correctAnswer: "Paris",
    difficulty: "easy",
    category: "place",
  },
  {
    question: "Which planet is known as the Red Planet?",
    options: ["Earth", "Mars", "Jupiter", "Saturn"],
    correctAnswer: "Mars",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "What is the largest ocean on Earth?",
    options: ["Atlantic", "Indian", "Pacific", "Arctic"],
    correctAnswer: "Pacific",
    difficulty: "easy",
    category: "nature",
  },
  {
    question: "Which animal is the largest land mammal?",
    options: ["Elephant", "Rhino", "Hippo", "Giraffe"],
    correctAnswer: "Elephant",
    difficulty: "easy",
    category: "nature",
  },
  {
    question: "Which sport is known as the 'king of sports'?",
    options: ["Cricket", "Basketball", "Football", "Tennis"],
    correctAnswer: "Football",
    difficulty: "easy",
    category: "sports",
  },
  {
    question: "What device do you use to browse the internet?",
    options: ["Washing Machine", "Microwave", "Computer", "Television"],
    correctAnswer: "Computer",
    difficulty: "easy",
    category: "tech",
  },
  {
    question: "Which color is made by mixing red and white?",
    options: ["Pink", "Purple", "Orange", "Brown"],
    correctAnswer: "Pink",
    difficulty: "easy",
    category: "general",
  },
  {
    question: "How many legs does a spider have?",
    options: ["6", "8", "4", "10"],
    correctAnswer: "8",
    difficulty: "easy",
    category: "nature",
  },
  {
    question: "Which country is home to the Great Wall?",
    options: ["India", "Japan", "China", "Thailand"],
    correctAnswer: "China",
    difficulty: "easy",
    category: "place",
  },
  {
    question: "What do bees make?",
    options: ["Milk", "Wax", "Honey", "Silk"],
    correctAnswer: "Honey",
    difficulty: "easy",
    category: "nature",
  },
  {
    question: "How many days are in a week?",
    options: ["5", "6", "7", "8"],
    correctAnswer: "7",
    difficulty: "easy",
    category: "general",
  },
  {
    question: "Which organ helps you see?",
    options: ["Heart", "Eye", "Ear", "Liver"],
    correctAnswer: "Eye",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "What is H2O commonly known as?",
    options: ["Salt", "Oxygen", "Water", "Hydrogen"],
    correctAnswer: "Water",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "Which shape has 3 sides?",
    options: ["Square", "Triangle", "Circle", "Rectangle"],
    correctAnswer: "Triangle",
    difficulty: "easy",
    category: "general",
  },
  {
    question: "Which fruit is yellow and curved?",
    options: ["Apple", "Orange", "Banana", "Grape"],
    correctAnswer: "Banana",
    difficulty: "easy",
    category: "nature",
  },
  {
    question: "What do you use to call someone?",
    options: ["Laptop", "Tablet", "Phone", "Speaker"],
    correctAnswer: "Phone",
    difficulty: "easy",
    category: "tech",
  },
  {
    question: "Which planet do we live on?",
    options: ["Mars", "Venus", "Earth", "Jupiter"],
    correctAnswer: "Earth",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "How many wheels does a bicycle have?",
    options: ["1", "2", "3", "4"],
    correctAnswer: "2",
    difficulty: "easy",
    category: "general",
  },
  {
    question: "What color is the sky on a clear day?",
    options: ["Red", "Blue", "Green", "Yellow"],
    correctAnswer: "Blue",
    difficulty: "easy",
    category: "nature",
  },
  {
    question: "Who painted the Mona Lisa?",
    options: [
      "Vincent van Gogh",
      "Leonardo da Vinci",
      "Picasso",
      "Michelangelo",
    ],
    correctAnswer: "Leonardo da Vinci",
    difficulty: "easy",
    category: "history",
  },
  {
    question: "Which season comes after summer?",
    options: ["Spring", "Autumn", "Winter", "Monsoon"],
    correctAnswer: "Autumn",
    difficulty: "easy",
    category: "nature",
  },
  {
    question: "What is 5 + 3?",
    options: ["6", "8", "9", "7"],
    correctAnswer: "8",
    difficulty: "easy",
    category: "general",
  },
  {
    question: "Which bird cannot fly?",
    options: ["Sparrow", "Pigeon", "Penguin", "Crow"],
    correctAnswer: "Penguin",
    difficulty: "easy",
    category: "nature",
  },
  {
    question: "What does a thermometer measure?",
    options: ["Speed", "Weight", "Temperature", "Length"],
    correctAnswer: "Temperature",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "How many continents are there?",
    options: ["5", "6", "7", "8"],
    correctAnswer: "7",
    difficulty: "easy",
    category: "place",
  },
  {
    question: "Which animal says 'moo'?",
    options: ["Dog", "Cat", "Cow", "Sheep"],
    correctAnswer: "Cow",
    difficulty: "easy",
    category: "nature",
  },
  {
    question: "Which language is most spoken in the world?",
    options: ["English", "Mandarin Chinese", "Spanish", "Hindi"],
    correctAnswer: "Mandarin Chinese",
    difficulty: "easy",
    category: "general",
  },
  {
    question: "What gas do we breathe in to live?",
    options: ["Carbon", "Oxygen", "Nitrogen", "Helium"],
    correctAnswer: "Oxygen",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "What do you use to brush your teeth?",
    options: ["Comb", "Toothbrush", "Spoon", "Pen"],
    correctAnswer: "Toothbrush",
    difficulty: "easy",
    category: "general",
  },
  {
    question: "What is the freezing point of water?",
    options: ["0°C", "10°C", "32°C", "100°C"],
    correctAnswer: "0°C",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "Which animal is known as man's best friend?",
    options: ["Cat", "Dog", "Horse", "Rabbit"],
    correctAnswer: "Dog",
    difficulty: "easy",
    category: "nature",
  },
  {
    question: "Which vegetable is orange and grows underground?",
    options: ["Potato", "Carrot", "Tomato", "Spinach"],
    correctAnswer: "Carrot",
    difficulty: "easy",
    category: "nature",
  },
  {
    question: "What is the main language spoken in Spain?",
    options: ["English", "French", "Spanish", "German"],
    correctAnswer: "Spanish",
    difficulty: "easy",
    category: "place",
  },
  {
    question: "Which shape is round and has no corners?",
    options: ["Triangle", "Square", "Circle", "Rectangle"],
    correctAnswer: "Circle",
    difficulty: "easy",
    category: "general",
  },
  {
    question: "Which sense is used to smell?",
    options: ["Touch", "Taste", "Smell", "Sight"],
    correctAnswer: "Smell",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "What color do you get by mixing red and blue?",
    options: ["Purple", "Orange", "Green", "Pink"],
    correctAnswer: "Purple",
    difficulty: "easy",
    category: "general",
  },
  {
    question: "What do you use to write on a blackboard?",
    options: ["Pen", "Chalk", "Crayon", "Marker"],
    correctAnswer: "Chalk",
    difficulty: "easy",
    category: "general",
  },
  {
    question: "What is the opposite of 'cold'?",
    options: ["Wet", "Hot", "Dry", "Warm"],
    correctAnswer: "Hot",
    difficulty: "easy",
    category: "general",
  },
  {
    question: "Which country is famous for pizza and pasta?",
    options: ["France", "Italy", "Mexico", "India"],
    correctAnswer: "Italy",
    difficulty: "easy",
    category: "place",
  },
  {
    question: "What do you wear on your feet?",
    options: ["Hat", "Gloves", "Shoes", "Shirt"],
    correctAnswer: "Shoes",
    difficulty: "easy",
    category: "general",
  },
  {
    question: "How many fingers does a human hand have?",
    options: ["4", "5", "6", "7"],
    correctAnswer: "5",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "What do cows eat?",
    options: ["Meat", "Fish", "Grass", "Fruits"],
    correctAnswer: "Grass",
    difficulty: "easy",
    category: "nature",
  },
  {
    question: "What is used to see faraway objects?",
    options: ["Telescope", "Microscope", "Magnifying Glass", "Glasses"],
    correctAnswer: "Telescope",
    difficulty: "easy",
    category: "tech",
  },
  {
    question: "Which natural satellite orbits the Earth?",
    options: ["Sun", "Moon", "Mars", "Venus"],
    correctAnswer: "Moon",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "Which instrument tells time?",
    options: ["Thermometer", "Clock", "Scale", "Compass"],
    correctAnswer: "Clock",
    difficulty: "easy",
    category: "general",
  },
  {
    question: "Which organ pumps blood?",
    options: ["Lungs", "Heart", "Liver", "Kidneys"],
    correctAnswer: "Heart",
    difficulty: "easy",
    category: "science",
  },
  {
    question: "What do you drink to stay hydrated?",
    options: ["Juice", "Water", "Soda", "Milk"],
    correctAnswer: "Water",
    difficulty: "easy",
    category: "general",
  },
  {
    question: "Which place is known for the Eiffel Tower?",
    options: ["London", "Paris", "New York", "Rome"],
    correctAnswer: "Paris",
    difficulty: "easy",
    category: "place",
  },
  {
    question: "What do birds use to fly?",
    options: ["Arms", "Wings", "Legs", "Fins"],
    correctAnswer: "Wings",
    difficulty: "easy",
    category: "nature",
  },
  {
    question: "Which element has the chemical symbol 'Fe'?",
    options: ["Fluorine", "Iron", "Fermium", "Francium"],
    correctAnswer: "Iron",
    difficulty: "medium",
    category: "science",
  },
  {
    question: "Who invented the telephone?",
    options: [
      "Thomas Edison",
      "Alexander Graham Bell",
      "Nikola Tesla",
      "Isaac Newton",
    ],
    correctAnswer: "Alexander Graham Bell",
    difficulty: "medium",
    category: "tech",
  },
  {
    question: "What is the currency of Japan?",
    options: ["Yuan", "Won", "Yen", "Baht"],
    correctAnswer: "Yen",
    difficulty: "medium",
    category: "place",
  },
  {
    question: "What is the capital of Canada?",
    options: ["Toronto", "Vancouver", "Ottawa", "Montreal"],
    correctAnswer: "Ottawa",
    difficulty: "medium",
    category: "place",
  },
  {
    question: "Which planet has the most moons?",
    options: ["Jupiter", "Saturn", "Uranus", "Neptune"],
    correctAnswer: "Saturn",
    difficulty: "medium",
    category: "science",
  },
  {
    question: "In which sport is the term 'love' used?",
    options: ["Tennis", "Badminton", "Cricket", "Baseball"],
    correctAnswer: "Tennis",
    difficulty: "medium",
    category: "sports",
  },
  {
    question: "What is the boiling point of water in Fahrenheit?",
    options: ["100°F", "180°F", "212°F", "250°F"],
    correctAnswer: "212°F",
    difficulty: "medium",
    category: "science",
  },
  {
    question: "Which country gifted the Statue of Liberty to the USA?",
    options: ["Germany", "France", "Italy", "Spain"],
    correctAnswer: "France",
    difficulty: "medium",
    category: "history",
  },
  {
    question: "Which desert is the largest in the world?",
    options: ["Gobi", "Sahara", "Arctic", "Antarctic"],
    correctAnswer: "Antarctic",
    difficulty: "medium",
    category: "nature",
  },
  {
    question: "Which continent is known as the 'Dark Continent'?",
    options: ["Asia", "Africa", "Australia", "Europe"],
    correctAnswer: "Africa",
    difficulty: "medium",
    category: "place",
  },
  {
    question: "Which blood type is known as the universal donor?",
    options: ["A", "B", "AB", "O Negative"],
    correctAnswer: "O Negative",
    difficulty: "medium",
    category: "science",
  },
  {
    question: "What is the hardest natural substance on Earth?",
    options: ["Gold", "Iron", "Diamond", "Platinum"],
    correctAnswer: "Diamond",
    difficulty: "medium",
    category: "science",
  },
  {
    question:
      "Which famous scientist developed the theory of general relativity?",
    options: ["Isaac Newton", "Galileo", "Albert Einstein", "Stephen Hawking"],
    correctAnswer: "Albert Einstein",
    difficulty: "medium",
    category: "science",
  },
  {
    question: "What is the longest river in the world?",
    options: ["Amazon", "Yangtze", "Mississippi", "Nile"],
    correctAnswer: "Nile",
    difficulty: "medium",
    category: "nature",
  },
  {
    question: "Which war ended with the Treaty of Versailles?",
    options: ["World War I", "World War II", "Cold War", "Vietnam War"],
    correctAnswer: "World War I",
    difficulty: "medium",
    category: "history",
  },
  {
    question: "What is the capital of South Korea?",
    options: ["Busan", "Seoul", "Incheon", "Daegu"],
    correctAnswer: "Seoul",
    difficulty: "medium",
    category: "place",
  },
  {
    question: "Which gas is most abundant in Earth’s atmosphere?",
    options: ["Oxygen", "Hydrogen", "Carbon Dioxide", "Nitrogen"],
    correctAnswer: "Nitrogen",
    difficulty: "medium",
    category: "science",
  },
  {
    question: "Which programming language is known for its snake logo?",
    options: ["Python", "Java", "Ruby", "C++"],
    correctAnswer: "Python",
    difficulty: "medium",
    category: "tech",
  },
  {
    question: "Which country hosted the 2016 Summer Olympics?",
    options: ["Japan", "Brazil", "Russia", "UK"],
    correctAnswer: "Brazil",
    difficulty: "medium",
    category: "sports",
  },
  {
    question: "Which bone is the longest in the human body?",
    options: ["Femur", "Tibia", "Humerus", "Spine"],
    correctAnswer: "Femur",
    difficulty: "medium",
    category: "science",
  },
  {
    question: "What is the name of the first man-made satellite?",
    options: ["Voyager", "Sputnik", "Apollo", "Hubble"],
    correctAnswer: "Sputnik",
    difficulty: "medium",
    category: "tech",
  },
  {
    question: "In which year did World War II end?",
    options: ["1940", "1945", "1950", "1939"],
    correctAnswer: "1945",
    difficulty: "medium",
    category: "history",
  },
  {
    question: "Which scientist is famous for the laws of motion?",
    options: ["Newton", "Einstein", "Hawking", "Curie"],
    correctAnswer: "Newton",
    difficulty: "medium",
    category: "science",
  },
  {
    question: "Which is the largest internal organ in the human body?",
    options: ["Brain", "Liver", "Heart", "Lung"],
    correctAnswer: "Liver",
    difficulty: "medium",
    category: "science",
  },
  {
    question: "Which metal is liquid at room temperature?",
    options: ["Mercury", "Aluminum", "Lead", "Iron"],
    correctAnswer: "Mercury",
    difficulty: "medium",
    category: "science",
  },
  {
    question: "Which city is known as the City of Canals?",
    options: ["Amsterdam", "Bangkok", "Venice", "Stockholm"],
    correctAnswer: "Venice",
    difficulty: "medium",
    category: "place",
  },
  {
    question: "Which vitamin is produced when the skin is exposed to sunlight?",
    options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"],
    correctAnswer: "Vitamin D",
    difficulty: "medium",
    category: "science",
  },
  {
    question: "What is the main ingredient in guacamole?",
    options: ["Cucumber", "Avocado", "Tomato", "Lettuce"],
    correctAnswer: "Avocado",
    difficulty: "medium",
    category: "general",
  },
  {
    question: "Which planet has a day longer than its year?",
    options: ["Venus", "Mars", "Mercury", "Jupiter"],
    correctAnswer: "Venus",
    difficulty: "medium",
    category: "science",
  },
  {
    question: "Which mountain is the tallest in the world?",
    options: ["K2", "Everest", "Kilimanjaro", "Makalu"],
    correctAnswer: "Everest",
    difficulty: "medium",
    category: "nature",
  },
  {
    question: "Which animal is a marsupial?",
    options: ["Panda", "Kangaroo", "Elephant", "Tiger"],
    correctAnswer: "Kangaroo",
    difficulty: "medium",
    category: "nature",
  },
  {
    question: "Which company created the iPhone?",
    options: ["Samsung", "Google", "Apple", "Microsoft"],
    correctAnswer: "Apple",
    difficulty: "medium",
    category: "tech",
  },
  {
    question: "Which instrument has 88 keys?",
    options: ["Violin", "Flute", "Piano", "Guitar"],
    correctAnswer: "Piano",
    difficulty: "medium",
    category: "general",
  },
  {
    question: "How many players are there in a baseball team?",
    options: ["7", "8", "9", "10"],
    correctAnswer: "9",
    difficulty: "medium",
    category: "sports",
  },
  {
    question: "Which famous ship sank in 1912?",
    options: ["Olympic", "Britannic", "Titanic", "Lusitania"],
    correctAnswer: "Titanic",
    difficulty: "medium",
    category: "history",
  },
  {
    question: "Which country is shaped like a boot?",
    options: ["Italy", "India", "Greece", "Turkey"],
    correctAnswer: "Italy",
    difficulty: "medium",
    category: "place",
  },
  {
    question: "What is the main function of white blood cells?",
    options: [
      "Oxygen transport",
      "Blood clotting",
      "Fighting infection",
      "Digestion",
    ],
    correctAnswer: "Fighting infection",
    difficulty: "medium",
    category: "science",
  },
  {
    question: "Which continent is the largest by land area?",
    options: ["Africa", "North America", "Asia", "Europe"],
    correctAnswer: "Asia",
    difficulty: "medium",
    category: "place",
  },
  {
    question: "Which famous scientist discovered penicillin?",
    options: [
      "Alexander Fleming",
      "Louis Pasteur",
      "Marie Curie",
      "Isaac Newton",
    ],
    correctAnswer: "Alexander Fleming",
    difficulty: "medium",
    category: "science",
  },
  {
    question: "What language has the most native speakers?",
    options: ["English", "Hindi", "Mandarin", "Spanish"],
    correctAnswer: "Mandarin",
    difficulty: "medium",
    category: "general",
  },
  {
    question: "How many chromosomes do humans have?",
    options: ["42", "44", "46", "48"],
    correctAnswer: "46",
    difficulty: "medium",
    category: "science",
  },
  {
    question: "Which blood cells help in clotting?",
    options: ["Red cells", "White cells", "Platelets", "Plasma"],
    correctAnswer: "Platelets",
    difficulty: "medium",
    category: "science",
  },
  {
    question: "What is the term for animals that eat only plants?",
    options: ["Carnivores", "Herbivores", "Omnivores", "Insectivores"],
    correctAnswer: "Herbivores",
    difficulty: "medium",
    category: "nature",
  },
  {
    question: "Which part of the cell contains genetic material?",
    options: ["Mitochondria", "Ribosome", "Nucleus", "Cytoplasm"],
    correctAnswer: "Nucleus",
    difficulty: "medium",
    category: "science",
  },
  {
    question: "What is the chemical formula for table salt?",
    options: ["NaCl", "KCl", "NaOH", "CaCO3"],
    correctAnswer: "NaCl",
    difficulty: "medium",
    category: "science",
  },
  {
    question: "Which Greek philosopher taught Alexander the Great?",
    options: ["Plato", "Socrates", "Aristotle", "Pythagoras"],
    correctAnswer: "Aristotle",
    difficulty: "medium",
    category: "history",
  },
  {
    question: "Which instrument is used to measure atmospheric pressure?",
    options: ["Thermometer", "Hygrometer", "Barometer", "Altimeter"],
    correctAnswer: "Barometer",
    difficulty: "medium",
    category: "science",
  },
  {
    question: "Which ocean is the deepest in the world?",
    options: ["Atlantic", "Indian", "Southern", "Pacific"],
    correctAnswer: "Pacific",
    difficulty: "medium",
    category: "nature",
  },
  {
    question: "What is the Heisenberg Uncertainty Principle related to?",
    options: ["Gravity", "Motion", "Quantum Mechanics", "Relativity"],
    correctAnswer: "Quantum Mechanics",
    difficulty: "hard",
    category: "science",
  },
  {
    question: "Which planet has the strongest magnetic field?",
    options: ["Earth", "Jupiter", "Saturn", "Neptune"],
    correctAnswer: "Jupiter",
    difficulty: "hard",
    category: "science",
  },
  {
    question:
      "Who was the first person to win two Nobel Prizes in different fields?",
    options: [
      "Albert Einstein",
      "Marie Curie",
      "Linus Pauling",
      "Bertrand Russell",
    ],
    correctAnswer: "Marie Curie",
    difficulty: "hard",
    category: "history",
  },
  {
    question: "What programming language is primarily used for AI research?",
    options: ["Python", "C#", "Java", "PHP"],
    correctAnswer: "Python",
    difficulty: "hard",
    category: "tech",
  },
  {
    question: "Which country has the most UNESCO World Heritage Sites?",
    options: ["China", "India", "Italy", "France"],
    correctAnswer: "Italy",
    difficulty: "hard",
    category: "place",
  },
  {
    question: "What is the rarest blood type in humans?",
    options: ["O-", "A-", "B+", "AB-"],
    correctAnswer: "AB-",
    difficulty: "hard",
    category: "science",
  },
  {
    question: "In what year did the Chernobyl disaster occur?",
    options: ["1982", "1986", "1990", "1991"],
    correctAnswer: "1986",
    difficulty: "hard",
    category: "history",
  },
  {
    question: "What is the capital of Kazakhstan?",
    options: ["Astana", "Almaty", "Tashkent", "Bishkek"],
    correctAnswer: "Astana",
    difficulty: "hard",
    category: "place",
  },
  {
    question: "What is the term for animals that are active during twilight?",
    options: ["Nocturnal", "Diurnal", "Crepuscular", "Vespertine"],
    correctAnswer: "Crepuscular",
    difficulty: "hard",
    category: "nature",
  },
  {
    question: "What is the square root of 729?",
    options: ["26", "27", "28", "29"],
    correctAnswer: "27",
    difficulty: "hard",
    category: "general",
  },
  {
    question: "Which African nation was formerly known as Abyssinia?",
    options: ["Sudan", "Ethiopia", "Somalia", "Kenya"],
    correctAnswer: "Ethiopia",
    difficulty: "hard",
    category: "history",
  },
  {
    question: "Which element has the highest melting point?",
    options: ["Iron", "Carbon", "Tungsten", "Platinum"],
    correctAnswer: "Tungsten",
    difficulty: "hard",
    category: "science",
  },
  {
    question: "What programming language was developed by Google?",
    options: ["Rust", "Swift", "Go", "Kotlin"],
    correctAnswer: "Go",
    difficulty: "hard",
    category: "tech",
  },
  {
    question: "Who wrote 'The Prince'?",
    options: ["Machiavelli", "Plato", "Descartes", "Voltaire"],
    correctAnswer: "Machiavelli",
    difficulty: "hard",
    category: "history",
  },
  {
    question:
      "Which tennis player has won the most Grand Slam titles (as of 2024)?",
    options: ["Rafael Nadal", "Novak Djokovic", "Roger Federer", "Andy Murray"],
    correctAnswer: "Novak Djokovic",
    difficulty: "hard",
    category: "sports",
  },
  {
    question: "What is the SI unit of electric capacitance?",
    options: ["Ohm", "Farad", "Tesla", "Watt"],
    correctAnswer: "Farad",
    difficulty: "hard",
    category: "science",
  },
  {
    question: "Which country has the longest coastline in the world?",
    options: ["Australia", "Russia", "Canada", "USA"],
    correctAnswer: "Canada",
    difficulty: "hard",
    category: "place",
  },
  {
    question: "What part of the brain controls balance?",
    options: ["Cerebrum", "Cerebellum", "Medulla", "Pons"],
    correctAnswer: "Cerebellum",
    difficulty: "hard",
    category: "science",
  },
  {
    question: "What is the chemical name for laughing gas?",
    options: [
      "Nitrogen Dioxide",
      "Nitrous Oxide",
      "Carbon Monoxide",
      "Methane",
    ],
    correctAnswer: "Nitrous Oxide",
    difficulty: "hard",
    category: "science",
  },
  {
    question: "Which civilization built Machu Picchu?",
    options: ["Aztec", "Maya", "Inca", "Olmec"],
    correctAnswer: "Inca",
    difficulty: "hard",
    category: "history",
  },
  {
    question: "What is the main ingredient in traditional Japanese miso soup?",
    options: ["Soybean paste", "Seaweed", "Rice", "Fish stock"],
    correctAnswer: "Soybean paste",
    difficulty: "hard",
    category: "general",
  },
  {
    question:
      "What is the second most spoken language in the world by native speakers?",
    options: ["English", "Hindi", "Spanish", "Arabic"],
    correctAnswer: "Spanish",
    difficulty: "hard",
    category: "general",
  },
  {
    question: "Which chess piece can only move diagonally?",
    options: ["Knight", "Rook", "Bishop", "Queen"],
    correctAnswer: "Bishop",
    difficulty: "hard",
    category: "general",
  },
  {
    question: "Which chemical element has the atomic number 92?",
    options: ["Uranium", "Plutonium", "Radium", "Cesium"],
    correctAnswer: "Uranium",
    difficulty: "hard",
    category: "science",
  },
  {
    question: "Which layer of the atmosphere contains the ozone layer?",
    options: ["Stratosphere", "Troposphere", "Mesosphere", "Exosphere"],
    correctAnswer: "Stratosphere",
    difficulty: "hard",
    category: "science",
  },
  {
    question: "What is the name of the galaxy closest to the Milky Way?",
    options: ["Andromeda", "Whirlpool", "Triangulum", "Sombrero"],
    correctAnswer: "Andromeda",
    difficulty: "hard",
    category: "science",
  },
  {
    question: "What is the capital of New Zealand?",
    options: ["Auckland", "Christchurch", "Wellington", "Hamilton"],
    correctAnswer: "Wellington",
    difficulty: "hard",
    category: "place",
  },
  {
    question: "What does the term 'CPU' stand for?",
    options: [
      "Central Processing Unit",
      "Core Programming Utility",
      "Computer Power Unit",
      "Central Power Unit",
    ],
    correctAnswer: "Central Processing Unit",
    difficulty: "hard",
    category: "tech",
  },
  {
    question: "Which physicist coined the term 'black hole'?",
    options: [
      "Stephen Hawking",
      "John Wheeler",
      "Roger Penrose",
      "Richard Feynman",
    ],
    correctAnswer: "John Wheeler",
    difficulty: "hard",
    category: "science",
  },
  {
    question: "Which chemical is commonly used as a preservative in food?",
    options: [
      "Sodium Chloride",
      "Benzoic Acid",
      "Citric Acid",
      "Ascorbic Acid",
    ],
    correctAnswer: "Benzoic Acid",
    difficulty: "hard",
    category: "science",
  },
  {
    question: "Who was the first female Prime Minister of the UK?",
    options: [
      "Margaret Thatcher",
      "Angela Merkel",
      "Theresa May",
      "Indira Gandhi",
    ],
    correctAnswer: "Margaret Thatcher",
    difficulty: "hard",
    category: "history",
  },
  {
    question: "What is the most abundant gas in the Sun?",
    options: ["Oxygen", "Nitrogen", "Hydrogen", "Helium"],
    correctAnswer: "Hydrogen",
    difficulty: "hard",
    category: "science",
  },
  {
    question:
      "What is the term for molten rock after it erupts from a volcano?",
    options: ["Magma", "Basalt", "Lava", "Slag"],
    correctAnswer: "Lava",
    difficulty: "hard",
    category: "nature",
  },
  {
    question:
      "Which branch of mathematics deals with vector spaces and linear mappings?",
    options: ["Calculus", "Linear Algebra", "Topology", "Statistics"],
    correctAnswer: "Linear Algebra",
    difficulty: "hard",
    category: "science",
  },
  {
    question: "Which planet rotates on its side relative to its orbit?",
    options: ["Mars", "Uranus", "Neptune", "Venus"],
    correctAnswer: "Uranus",
    difficulty: "hard",
    category: "science",
  },
  {
    question: "Which treaty ended World War II?",
    options: [
      "Treaty of Versailles",
      "Treaty of Paris",
      "Potsdam Agreement",
      "San Francisco Treaty",
    ],
    correctAnswer: "San Francisco Treaty",
    difficulty: "hard",
    category: "history",
  },
  {
    question: "Which is the only continent without reptiles or snakes?",
    options: ["Antarctica", "Europe", "Asia", "Australia"],
    correctAnswer: "Antarctica",
    difficulty: "hard",
    category: "nature",
  },
  {
    question: "What is the maximum score in a single frame of snooker?",
    options: ["147", "155", "150", "140"],
    correctAnswer: "147",
    difficulty: "hard",
    category: "sports",
  },
  {
    question: "What does HTTP stand for?",
    options: [
      "Hypertext Transfer Protocol",
      "High Tech Transfer Protocol",
      "Hybrid Transfer Protocol",
      "Hyper Terminal Trace Protocol",
    ],
    correctAnswer: "Hypertext Transfer Protocol",
    difficulty: "hard",
    category: "tech",
  },
  {
    question: "Which vitamin is also known as ascorbic acid?",
    options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"],
    correctAnswer: "Vitamin C",
    difficulty: "hard",
    category: "science",
  },
  {
    question: "Which particle has no electrical charge?",
    options: ["Electron", "Proton", "Neutron", "Photon"],
    correctAnswer: "Neutron",
    difficulty: "hard",
    category: "science",
  },
  {
    question: "What is the capital of Mongolia?",
    options: ["Astana", "Ulaanbaatar", "Tashkent", "Lhasa"],
    correctAnswer: "Ulaanbaatar",
    difficulty: "hard",
    category: "place",
  },
  {
    question: "Who was the first computer programmer?",
    options: ["Ada Lovelace", "Alan Turing", "Charles Babbage", "Grace Hopper"],
    correctAnswer: "Ada Lovelace",
    difficulty: "hard",
    category: "tech",
  },
  {
    question:
      "Which organ is responsible for filtering blood in the human body?",
    options: ["Heart", "Liver", "Lungs", "Kidney"],
    correctAnswer: "Kidney",
    difficulty: "hard",
    category: "science",
  },
  {
    question: "What is the highest mountain in Africa?",
    options: ["Mount Kenya", "Kilimanjaro", "Ras Dashen", "Simien Mountains"],
    correctAnswer: "Kilimanjaro",
    difficulty: "hard",
    category: "nature",
  },
  {
    question: "Which Shakespeare play features the character Iago?",
    options: ["Hamlet", "Othello", "Macbeth", "King Lear"],
    correctAnswer: "Othello",
    difficulty: "hard",
    category: "general",
  },
  {
    question:
      "Which part of the electromagnetic spectrum has the shortest wavelength?",
    options: ["Gamma rays", "X-rays", "Ultraviolet", "Infrared"],
    correctAnswer: "Gamma rays",
    difficulty: "hard",
    category: "science",
  },
];
